[package]
name = "iceoryx2-request-response"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "1.3.3"
clap = { version = "4.5.23", features = ["derive"] }
crossbeam-channel = "0.5.14"
ctrlc = "3.4"
iceoryx2 = "0.5.0"
num_enum = "0.7.3"
serde = "1.0"
